#!/usr/bin/env bash

# Add a user to the remote system, optionally specifying an additional group of
# membership. Requires root access on the remote system.

set -e || exit 1
set -o pipefail
set -o nounset

function usage () { echo "usage: `basename $0` remotesys username [ group ]" ; }
function usageerr () { usage >&2 ; return 1 ; }

[ $# -ge 2 ] || usageerr
[ $# -le 3 ] || usageerr
SYS="$1"
USERNAME="$2"
shift 2
# FIXME --disabled-password isn't supported on redhat; we'd like to use it
ssh -F conf/ssh_config -t "root@$SYS" adduser "$USERNAME"
[ $# -eq 0 ] || ssh -F conf/ssh_config -n "root@$SYS" usermod -G "$1" -a "$USERNAME"
