#!/usr/bin/env bash

set -e || { echo "Couldn't set -e, exiting" >&2 ; exit 1 ; }
set -o nounset

function usage () { echo "Usage: `basename $0` tapdev [ tapaddr ]" ; }
function usageerr () { usage >&2 ; return 1 ; }

[ $# -gt 0 ] || usageerr
TAPDEV="$1"
TAPIP=""
[ $# -lt 3 ] || usageerr
[ $# -eq 1 ] || TAPIP="$2"

ip l l dev $TAPDEV > /dev/null 2>&1 || sudo tunctl -t $TAPDEV -u $USER
ip -o l l dev $TAPDEV 2>&1 | grep UP > /dev/null || sudo ip l s dev $TAPDEV up
[ -z "$TAPIP" ] || ip -o a l dev $TAPDEV 2>&1 | grep $TAPIP > /dev/null || sudo ip a a $TAPIP dev $TAPDEV
